# Generated by Django 4.0.2 on 2022-02-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('app_label', models.CharField(max_length=256)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'app_label')},
            },
        ),
    ]
